(function(){
  const W=window, D=document;
  const LS='pratyush_kr_master_addon_v1';
  const defaults={
    vendor:[['V0001','Anand Enterprises','Bengaluru','GST Registered','Active'],['V0002','Demo Polymers','Mysuru','Raw Material','Active']],
    customer:[['C0001','Demo Retailer','Bengaluru','B2B','Active'],['C0002','Demo Distributor','Maddur','Distributor','Active']],
    pricelist:[['PL01','Standard Purchase','INR','Purchase','Active'],['PL02','Standard Sales','INR','Sales','Active']],
    plant:[['PLT001','Bidadi Plant','Bidadi','Manufacturing','Active'],['PLT002','Maddur New Plant','Maddur','Manufacturing','Active'],['PLT003','Hulivana Plant','Hulivana','Manufacturing','Active']],
    bom:[['BOM001','EN-5002 Ready Torch','FG-TORCH-RED','5 components','Active'],['BOM002','EN-5002 Body Red','SFG-BODY-RED','3 components','Active']],
    uom:[['PCS','Pieces',0,'Count','Active'],['KG','Kilogram',3,'Weight','Active'],['BOX','Box',0,'Count','Active'],['CTN','Carton',0,'Count','Active']],
    currency:[['INR','Indian Rupee','₹','1.0000','Active'],['USD','US Dollar','$','83.5000','Active']],
    uomconv:[['PCS-BOX','PCS','BOX','10','Active'],['BOX-CTN','BOX','CTN','10','Active']],
    driver:[['DRV001','Ramesh Kumar','KA01AB1234','9876543210','Active'],['DRV002','Suresh','KA42CD5678','9876501234','Active']],
    vehicle:[['VEH001','KA01AB1234','Tata Ace','Goods','Active'],['VEH002','KA42CD5678','Ashok Leyland Dost','Goods','Active']],
    transporter:[['TVT01','Mini Truck','0-2 MT','Local','Active'],['TVT02','LCV','2-7.5 MT','Inter-plant','Active']],
    supervisor:[['SUP001','Manoj','Bidadi','Store Supervisor','Active'],['SUP002','Krishna','Maddur','Warehouse Supervisor','Active']],
    security:[['SEC001','Praveen','Bidadi Main Gate','Security','Active'],['SEC002','Ravi','Maddur Gate','Security','Active']],
    colour:[['CLR001','Red','#ef4444','Body / Finished Goods','Active'],['CLR002','Green','#22c55e','Body / Finished Goods','Active'],['CLR003','Yellow','#eab308','Body / Finished Goods','Active'],['CLR004','Purple','#8b5cf6','Body / Finished Goods','Active'],['CLR005','Sky Blue','#38bdf8','Body / Finished Goods','Active'],['CLR006','Orange','#f97316','Body / Finished Goods','Active']]
  };
  let store; try{store=JSON.parse(localStorage.getItem(LS)||'null')||JSON.parse(JSON.stringify(defaults));}catch(e){store=JSON.parse(JSON.stringify(defaults));}
  const save=()=>localStorage.setItem(LS,JSON.stringify(store));
  const defs={
    vendor:['Vendor Master','Manage vendors',['Code','Vendor Name','City','Category','Status']],
    customer:['Customer Master','Manage customers',['Code','Customer Name','City','Type','Status']],
    pricelist:['Price List Master','Manage purchase and sales price lists',['Code','Price List','Currency','Type','Status']],
    plant:['Plant Master','Manage manufacturing and storage plants',['Code','Plant Name','Location','Type','Status']],
    bom:['BOM Master','Manage bills of material',['BOM Code','BOM Name','Parent Item','Components','Status']],
    uom:['UOM Master','Manage units of measure',['Code','Name','Decimals','Category','Status']],
    currency:['Currency Master','Manage transaction currencies',['Code','Currency','Symbol','Rate','Status']],
    uomconv:['UOM Conversions','Manage conversion factors',['Code','From UOM','To UOM','Factor','Status']],
    driver:['Driver Master','Manage vehicle drivers',['Code','Driver Name','Vehicle No','Phone','Status']],
    vehicle:['Vehicle Master','Manage company and transporter vehicles',['Code','Vehicle No','Model','Type','Status']],
    transporter:['Transporter Vehicle Types','Manage logistics vehicle types',['Code','Vehicle Type','Capacity','Usage','Status']],
    supervisor:['Supervisor Master','Manage stock and warehouse supervisors',['Code','Supervisor','Plant','Designation','Status']],
    security:['Security Master','Manage security personnel',['Code','Name','Gate / Plant','Role','Status']],
    colour:['Colour Master','Manage item colours',['Code','Colour','Hex / Ref','Usage','Status']]
  };
  const routes=Object.keys(defs).map(k=>'master_'+k);
  function esc(x){return String(x??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s]));}
  function rowTable(key){const df=defs[key], q=(D.querySelector('#prkMQ')?.value||'').toLowerCase(); const rows=store[key].filter(r=>!q||r.join(' ').toLowerCase().includes(q));return `<div class="table"><table><thead><tr>${df[2].map(h=>`<th>${h}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map((r,i)=>`<tr>${r.map((c,j)=>`<td>${j===r.length-1?`<span class="prk-master-pill">${esc(c)}</span>`:esc(c)}</td>`).join('')}<td><button class="btn" onclick="window.PrkMaster.edit('${key}',${store[key].indexOf(r)})">Edit</button></td></tr>`).join('')||`<tr><td colspan="${df[2].length+1}" class="empty">No records</td></tr>`}</tbody></table></div>`;}
  function page(key){const df=defs[key];return `${W.head?W.head(df[0],df[1],`<button class="btn primary" onclick="window.PrkMaster.add('${key}')">+ New</button><button class="btn" onclick="window.PrkMaster.exportCsv('${key}')">Export CSV</button>`):`<div class="head"><div><h1>${df[0]}</h1><p>${df[1]}</p></div></div>`}<div class="card pad"><div class="prk-master-toolbar"><input id="prkMQ" class="grow" placeholder="Search ${df[0].toLowerCase()}..." oninput="window.PrkMaster.refresh('${key}')"><select id="prkStatus" onchange="window.PrkMaster.refresh('${key}')"><option>All status</option><option>Active</option><option>Inactive</option></select></div><div id="prkMasterRows">${rowTable(key)}</div><div class="prk-master-note">Dummy/UAT master data. Existing inventory modules are unchanged.</div></div>`;}
  function dashboard(){const cards=[['items','Item Master',()=>W.d?.items?.length||5,'#2563eb'],['vendor','Vendor Master',()=>store.vendor.length,'#9333ea'],['customer','Customer Master',()=>store.customer.length,'#16a34a'],['pricelist','Price List Master',()=>store.pricelist.length,'#0f9f8f'],['warehouse','Warehouse Master',()=>W.d?.wh?.length||5,'#f97316'],['plant','Plant Master',()=>store.plant.length,'#ef4444'],['bom','BOM Master',()=>store.bom.length,'#14b8a6'],['uom','UOM Master',()=>store.uom.length,'#0ea5e9'],['currency','Currency Master',()=>store.currency.length,'#64748b'],['uomconv','UOM Conversions',()=>store.uomconv.length,'#06b6d4'],['driver','Driver Master',()=>store.driver.length,'#db2777'],['vehicle','Vehicle Master',()=>store.vehicle.length,'#ca8a04'],['transporter','Transporter Vehicle Types',()=>store.transporter.length,'#ea580c'],['supervisor','Supervisor Master',()=>store.supervisor.length,'#4f46e5'],['security','Security Master',()=>store.security.length,'#475569'],['colour','Colour Master',()=>store.colour.length,'#c026d3']];return `${W.head?W.head('Master Data','All inventory and administration masters'):''}<div class="prk-master-grid">${cards.map(c=>`<div class="prk-master-card" onclick="${c[0]==='items'?"go('items')":c[0]==='warehouse'?"go('warehouse')":`window.PrkMaster.open('${c[0]}')`}"><div class="top" style="background:${c[3]}"><span>${c[2]()}</span><span>▣</span></div><div class="body"><b>${c[1]}</b><small>Manage ${c[1].replace(' Master','').toLowerCase()}</small></div></div>`).join('')}</div>`;}
  function addNav(){const nav=D.querySelector('#nav'); if(!nav||D.querySelector('[data-prk-master-group]'))return; const wrap=D.createElement('div');wrap.setAttribute('data-prk-master-group','1');wrap.innerHTML=`<div class="sec">Master Data</div><button class="nav" onclick="window.PrkMaster.dashboard()"><span class="ic">▦</span><span><b>Master Dashboard</b><small>All Masters</small></span></button>${[['items','◈','Item Master'],['vendor','▤','Vendor Master'],['customer','♙','Customer Master'],['pricelist','◇','Price List Master'],['warehouse','▣','Warehouse Master'],['plant','▥','Plant Master'],['bom','▤','BOM Master'],['uom','⌁','UOM Master'],['currency','₹','Currency Master'],['uomconv','⇄','UOM Conversions'],['driver','♙','Driver Master'],['vehicle','◇','Vehicle Master'],['transporter','▤','Transporter Vehicle Types'],['supervisor','♙','Supervisor Master'],['security','⚙','Security Master'],['colour','◉','Colour Master']].map(x=>`<button class="nav" data-q="${x[2].toLowerCase()} master data" onclick="${x[0]==='items'?"go('items')":x[0]==='warehouse'?"go('warehouse')":`window.PrkMaster.open('${x[0]}')`}"><span class="ic">${x[1]}</span><span><b>${x[2]}</b><small>Master Data</small></span></button>`).join('')}`;nav.appendChild(wrap);}
  function open(key){location.hash='master_'+key;renderMaster(key);}
  function renderMaster(key){if(!defs[key])return; const p=D.querySelector('#page'),c=D.querySelector('#crumb');if(c)c.innerHTML=`${defs[key][0]}<small>Master Data</small>`;if(p)p.innerHTML=page(key);}
  function refresh(key){const target=D.querySelector('#prkMasterRows');if(!target)return; const status=D.querySelector('#prkStatus')?.value||'All status',q=(D.querySelector('#prkMQ')?.value||'').toLowerCase();const df=defs[key];const rows=store[key].filter(r=>(status==='All status'||r[r.length-1]===status)&&(!q||r.join(' ').toLowerCase().includes(q)));target.innerHTML=`<div class="table"><table><thead><tr>${df[2].map(h=>`<th>${h}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map(r=>{const idx=store[key].indexOf(r);return `<tr>${r.map((c,j)=>`<td>${j===r.length-1?`<span class="prk-master-pill">${esc(c)}</span>`:esc(c)}</td>`).join('')}<td><button class="btn" onclick="window.PrkMaster.edit('${key}',${idx})">Edit</button></td></tr>`}).join('')||`<tr><td colspan="${df[2].length+1}" class="empty">No records</td></tr>`}</tbody></table></div>`;}
  function form(key,idx){const df=defs[key],r=idx==null?Array(df[2].length).fill(''):store[key][idx];return `<div class="mh"><h3>${idx==null?'New':'Edit'} ${df[0]}</h3><button class="btn x" onclick="window.PrkMaster.close()">✕</button></div><div class="mb"><div class="form">${df[2].map((h,i)=>`<div class="field"><label>${h}</label>${h==='Status'?`<select id="pm${i}"><option ${r[i]==='Active'?'selected':''}>Active</option><option ${r[i]==='Inactive'?'selected':''}>Inactive</option></select>`:`<input id="pm${i}" value="${esc(r[i])}">`}</div>`).join('')}</div></div><div class="mf"><button class="btn" onclick="window.PrkMaster.close()">Cancel</button><button class="btn primary" onclick="window.PrkMaster.save('${key}',${idx==null?'null':idx})">Save</button></div>`;}
  function add(key){D.querySelector('#modal').innerHTML=`<div class="modalbg"><div class="modal">${form(key,null)}</div></div>`;}
  function edit(key,idx){D.querySelector('#modal').innerHTML=`<div class="modalbg"><div class="modal">${form(key,idx)}</div></div>`;}
  function close(){D.querySelector('#modal').innerHTML='';}
  function saveRow(key,idx){const df=defs[key],r=df[2].map((_,i)=>D.querySelector('#pm'+i)?.value.trim()||''); if(!r[0]||!r[1]){W.toast?W.toast('Code and name are required'):alert('Code and name are required');return;} if(idx==null&&store[key].some(x=>x[0].toLowerCase()===r[0].toLowerCase())){W.toast?W.toast('Duplicate code blocked'):alert('Duplicate code blocked');return;} if(idx==null)store[key].push(r);else store[key][idx]=r;save();close();renderMaster(key);if(W.toast)W.toast(defs[key][0]+' saved');}
  function exportCsv(key){const df=defs[key],rows=[df[2],...store[key]],text=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),a=D.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=key+'-master.csv';a.click();URL.revokeObjectURL(a.href);}
  function masterDashboard(){location.hash='master_dashboard';const p=D.querySelector('#page'),c=D.querySelector('#crumb');if(c)c.innerHTML='Master Data<small>Master Dashboard</small>';if(p)p.innerHTML=dashboard();}
  W.PrkMaster={open,refresh,add,edit,close,save:saveRow,exportCsv,dashboard:masterDashboard};
  const oldBuild=W.buildNav;if(typeof oldBuild==='function')W.buildNav=function(){oldBuild.apply(this,arguments);setTimeout(addNav,0)};
  const oldRender=W.render;if(typeof oldRender==='function')W.render=function(){const r=location.hash.slice(1);if(r==='master_dashboard'){masterDashboard();addNav();return;}if(r.startsWith('master_')){renderMaster(r.replace('master_',''));addNav();return;}oldRender.apply(this,arguments);addNav();};
  W.addEventListener('hashchange',()=>{const r=location.hash.slice(1);if(r==='master_dashboard')masterDashboard();else if(r.startsWith('master_'))renderMaster(r.replace('master_',''));});
  addNav();
})();